name: NPM Version Manager
on:
  push:
    branches: [ master ]
     
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.SECRET_KEY}}
      - run: git config --global user.name 'hervegondie'
      - run: git config --global user.email 'gondie.herve@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
