name: NPM Version Manager
on:
  push:
    branches: [ master ]
  pull request:
    branches: [ master ]
      
jobs:
   version:
   build:
   
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
       
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2

        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.NPM_VERSION_SECRET }}
      - run: git config --global user.name 'hgondie'
      - run: git config --global user.email 'herve.gondie@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      
